# FROM ubuntu:22.04
# image 'mcr.microsoft.com/devcontainers/base:alpine' locally
FROM nixos/nix
RUN nix-channel --update

# RUN nix-build -A pythonFull '<nixpkgs>'
# RUN nix-build -A python3 FAILS!
COPY .Rprofile /
COPY shell.nix /
RUN nix-build /shell.nix
# RUN nix-build rPackages.ggplot2 rPackages.pacman rPackages.jsonlite rPackages.languageserver rPackages.httpgd rPackages.rmarkdown rPackages.dplyr rPackages.shiny rPackages.plotly rPackages.usethis
