# FROM ubuntu:22.04
# image 'mcr.microsoft.com/devcontainers/base:alpine' locally

# FROM nixos/nix
FROM nixpkgs/devcontainer

# RUN nix-channel --update

# to get past this error
# message: 'Command in container failed: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null'
# https://github.com/NixOS/nixpkgs/issues/174633
# RUN touch /etc/os-release
# COPY _etc_os-release /etc/os-release
# cat /etc/os-release || cat /usr/lib/os-release

# RUN nix-build -A pythonFull '<nixpkgs>'
# RUN nix-build -A python3 FAILS!
COPY .Rprofile /
COPY default.nix /
# COPY shell.nix /
RUN nix-build /default.nix
# RUN nix-build /shell.nix
# RUN nix-build -p rPackages.jsonlite rPackages.languageserver rPackages.httpgd rPackages.rmarkdown rPackages.dplyr rPackages.shiny rPackages.plotly rPackages.usethis


# Step 2 - Set arguments and environment variables
# Define arguments
ARG VENV_NAME=VENV_NAME
ARG R_VERSION_MAJOR=4
ARG R_VERSION_MINOR=3
ARG R_VERSION_PATCH=2
ARG DEBIAN_FRONTEND=noninteractive
ARG CRAN_MIRROR=https://cran.rstudio.com/
ARG QUARTO_VER="1.4.590"

# Define environment variables
ENV VENV_NAME=$VENV_NAME
ENV R_VERSION_MAJOR=$R_VERSION_MAJOR
ENV R_VERSION_MINOR=$R_VERSION_MINOR
ENV R_VERSION_PATCH=$R_VERSION_PATCH
ENV QUARTO_VER=$QUARTO_VER
ENV CONFIGURE_OPTIONS="--with-cairo --with-jpeglib --enable-R-shlib --with-blas --with-lapack"
ENV TZ=UTC
ENV CRAN_MIRROR=$CRAN_MIRROR

# RUN locale-gen en_US.UTF-8

WORKDIR ~/

RUN mkdir settings
COPY packages.json install_packages.R requirements.txt install_quarto.sh ./settings/

# RUN Rscript ./settings/install_packages.R

# Installing Quarto
#RUN bash ./settings/install_quarto.sh $QUARTO_VER


# Step 5 - Set Python Environment and install radian
# RUN python3 -m venv /opt/$VENV_NAME  \
#     && export PATH=/opt/$VENV_NAME/bin:$PATH \
#     && echo "source /opt/$VENV_NAME/bin/activate" >> ~/.bashrc \
#     && echo "alias r='radian --profile=/.Rprofile'" >> ~/.bashrc


# RUN pip3 install -r ./settings/requirements.txt

# https://www.freedesktop.org/software/systemd/man/latest/os-release.html
COPY _etc_os-release /etc/os-release
