# Setting an R environment from scratch
# Step 1 - Import base image
FROM ubuntu:22.04

RUN nix-shell -p R radianWrapper rPackages.ggplot2 rPackages.pacman rPackages.jsonlite rPackages.languageserver rPackages.httpgd rPackages.rmarkdown rPackages.dplyr rPackages.shiny rPackages.plotly rPackages.usethis

